# Generated by Django 2.0.2 on 2018-02-22 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wisdom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_data', models.CharField(max_length=700)),
            ],
        ),
    ]
